version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 22
    commands:
      - echo Installing dependencies...
      - npm install -g pnpm
      - pnpm install
  build:
    commands:
      - echo Building application...
      - pnpm run build
  post_build:
    commands:
      - echo Build completed on `date`

artifacts:
  files:
    - package.json
    - pnpm-lock.yaml       # <-- Important!
    - .ebextensions/**/*
    - dist/**/*
    - node_modules/**/*
    - prisma/**/*
  discard-paths: no